ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from home.views import login_view, guest_register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('products/', include(("products.urls", 'products'),namespace='products')),
    path('search/', include(("search.urls", 'search'),namespace='search')),
    path('carts/', include(("carts.urls", 'carts'),namespace='carts')),
    path('', include('home.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/home/urls.py
from django.urls import path, re_path
from home import views

urlpatterns = [
    path('', views.home_View, name='home'),
    path('contact/', views.contact_View, name='contact'),
    path('about/', views.about_View, name='about'),
    path('register/', views.register_view, name='register'),
]

ecommerce/products/urls.py
from django.urls import path, re_path
from products import views

urlpatterns = [
    path('', views.ProductView.as_view(), name='list'),
    # path('product/<int:pk>/', views.product_details_view, name='details'),
    re_path('(?P<slug>[-\w]+)/', views.product_details_slug_view.as_view(), name='details'),
]

ecommerce/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

ecommerce/templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

ecommerce/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as products_list_url  %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'register' as register_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'carts:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-light sticky-top mb-3" style="background-color: #e3f2fd;">
  <div class="container">
  <a class="navbar-brand" href="{{home_url}}">
      <i class="fa fa-contao"></i>
    {% if brand_name %}{{ brand_name }}{% else %}LKM eCommerce{% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {% endif %}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item  {% if request.path == products_list_url %} active {% endif %}">
        <a class="nav-link" href="{{ products_list_url }}">Products</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == about_url %} active {% endif %}">
        <a class="nav-link" href="{{ about_url }}">About Us</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item {% if request.path == login_url %} active {% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
      <li class="nav-item {% if request.path == register_url %} active {% endif %}">
        <a class="nav-link" href="{{ register_url }}">Sign Up</a>
      </li>
      {% endif %}
      <li class="nav-item {% if request.path == cart_url %} active {% endif %}">
        <a class="nav-link" href="{{ cart_url }}"> {{request.session.cart_item }} <i class="fa fa-shopping-cart"></i></a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
  </ul>

    {% include 'search/snippets/search_form.html' %}
  </div>
    </div>
</nav>