ecommerce/carts/urls.py
from django.urls import path
from carts import views


urlpatterns = [
    path('', views.cart_home_view, name='home'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', views.checkout_view, name='checkout'),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from home.views import login_view, guest_register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('products/', include(("products.urls", 'products'),namespace='products')),
    path('search/', include(("search.urls", 'search'),namespace='search')),
    path('carts/', include(("carts.urls", 'carts'),namespace='carts')),
    path('', include('home.urls')),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/home/urls.py
from django.urls import path, re_path
from home import views

urlpatterns = [
    path('', views.home_View, name='home'),
    path('contact/', views.contact_View, name='contact'),
    path('about/', views.about_View, name='about'),
    path('register/', views.register_view, name='register'),
]

ecommerce/carts/models.py
from django.conf import settings
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed
# Create your models here.
User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id = request.session.get("cart_id",None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count()==1:
            new_obj = False
            cart_obj =qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj=Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj


    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User,null=True, blank=True,on_delete=models.DO_NOTHING)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100000, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100000, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)



def m2m_changed_cart_reciver(sender, instance, action ,*args, **kwargs):
    if action =='post_add' or action =='post_remove' or action =='post_clear':
        products = instance.products.all()
        total = 0
        for p in products:
            total = total+ p.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_reciver, sender=Cart.products.through)


def pre_save_cart_reciver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal + 10
    else:
        instance.subtotal = 0.00
pre_save.connect(pre_save_cart_reciver, sender=Cart)

ecommerce/carts/views.py
from django.shortcuts import render, redirect
from .models import Cart
from products.models import Product
from orders.models import Order
from django.contrib.auth.decorators import login_required
from home.forms import LoginForm, GuestForm
from home.models import GuestEmail
from billing.models import BillingProfile
# Create your views here.

def cart_home_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request,'carts/cart_home.html',{"cart":cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print('Product not avilable...')
            return redirect('carts:home')
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_item'] = cart_obj.products.count()
        # return redirect(product_obj.get_absolute_url())
    return redirect('carts:home')


def checkout_view(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")
    else:
        order_obj,new_order_obj = Order.objects.get_or_create(cart=cart_obj)
    user = request.user
    billing_profile = None
    login_form = LoginForm()
    guest_form = GuestForm()
    guest_email_id = request.session.get('guest_email_id')
    if user.is_authenticated:
        billing_profile, billing_profile_created = BillingProfile.objects.get_or_create(user=user, email=user.email)
    elif guest_email_id is not None:
        guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
        billing_profile, billing_guest_profile_created = BillingProfile.objects.get_or_create( email=guest_email_obj.email)
    else:
        pass
    context={
        "object":order_obj,
        "billing_profile":billing_profile,
        "login_form":login_form,
        "guest_form":guest_form
    }

    return render(request, 'carts/checkout.html',context)

ecommerce/templates/carts/cart_home.html
{% extends 'base.html' %}

{% block title %} MyCart {% endblock %}

    {% block content %}
      <h1>Cart</h1>
      {% if cart.products.exists %}
      <table class="table">
        <thead>
          <tr>
            <th>No</th>
            <th>Product Name</th>
            <th>Price</th>
          </tr>
        </thead>
        {% for product in cart.products.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
          {% include 'products/snippets/update_to_cart.html' with product=product cart=cart in_cart=True %}</td>
          <td>{{ product.price }}</td>
        </tr>
        {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td><b>Subtotal:</b>{{cart.subtotal}}</td>
          </tr>
          <tr>
            <td colspan="2"></td>
          <td><b>Total:</b>{{cart.total}}</td>
        </tr>
        <tr>
          <td colspan="2"></td>
          <td><a href="{% url 'carts:checkout' %}" class="btn btn-success btn-lg">Checkout</a></td>
      </tr>
      </table>
      {% else %}
      <p class="lead">Cart Is Empty</p>
      {% endif %}

    {% endblock %}

ecommerce/templates/carts/checkout.html
{% extends 'base.html' %}

{% block title %} checkout page {% endblock %}

      {% block content %}
          {% if not billing_profile %}
          <div class="raw" align='center'>
            <div class="col-12 col-md-6" align='left'>
            {% include 'user/snippets/login_form.html' with form=login_form next_url=request.build_absolute_uri %}
            </div>
            <div class="col-12 col-md-6" align='left'>
            <legend align='center'>Login As Guest</legend>{% url 'guest_register' as guest_register_url %}
            {% include 'user/snippets/login_form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
            </div>
          </div>
          {% else %}
              <h1>Checkout</h1>
              <h5>Cart Total: {{ object.cart.total }}</h5>
              <h5>Shipping Total: {{ object.shipping_total }}</h5>
              <h5>Order Total: {{ object.total }}</h5>
          {% endif %}
      {% endblock %}